
export const projects: object[] = [
     {
        userId: 1,
        title: 'This is my demo Project',
        category: 'collectables',
        subTitle: 'Let make this a reality and collect!',
        image: 'https://picsum.photos/400/250',
        targetLaunchDate: '01-2023',
        fundingCurrent: 1400,
        fundingGoal: 10000,
        story: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eleifend finibus ultrices. Donec volutpat venenatis auctor. Nam vehicula massa nulla, vel scelerisque velit vehicula vitae. Vestibulum efficitur fringilla diam eget efficitur. Nunc suscipit est nec tortor porta tristique. Nam vestibulum sem cursus viverra blandit. Nunc quis pellentesque enim. Donec porttitor quam ac auctor auctor. In efficitur ultricies lorem eu pellentesque.',
      },
     {
        userId: 1,
        title: 'DEMO-LITION: THE GAME!',
        category: 'games',
        subTitle: 'Get ready to demo your ignition!',
        image: 'https://picsum.photos/400/250',
        targetLaunchDate: '07-2025',
        fundingCurrent: 90,
        fundingGoal: 3000000,
        story: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eleifend finibus ultrices. Donec volutpat venenatis auctor. Nam vehicula massa nulla, vel scelerisque velit vehicula vitae. Vestibulum efficitur fringilla diam eget efficitur. Nunc suscipit est nec tortor porta tristique. Nam vestibulum sem cursus viverra blandit. Nunc quis pellentesque enim. Donec porttitor quam ac auctor auctor. In efficitur ultricies lorem eu pellentesque.',
      },
     {
        userId: 1,
        title: 'This is my demo Project',
        category: 'collectables',
        subTitle: 'Let make this a reality and collect!',
        image: 'https://picsum.photos/400/250',
        targetLaunchDate: '09-2022',
        fundingCurrent: 300400,
        fundingGoal: 20000,
        story: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eleifend finibus ultrices. Donec volutpat venenatis auctor. Nam vehicula massa nulla, vel scelerisque velit vehicula vitae. Vestibulum efficitur fringilla diam eget efficitur. Nunc suscipit est nec tortor porta tristique. Nam vestibulum sem cursus viverra blandit. Nunc quis pellentesque enim. Donec porttitor quam ac auctor auctor. In efficitur ultricies lorem eu pellentesque.',
      },
     {
        userId: 5,
        title: 'Candy Kane\'s',
        category: 'consumables',
        subTitle: 'Bringing you the best sweets have to offer.',
        image: 'https://picsum.photos/400/250',
        targetLaunchDate: '12-2022',
        fundingCurrent: 3900,
        fundingGoal: 5000,
        story: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eleifend finibus ultrices. Donec volutpat venenatis auctor. Nam vehicula massa nulla, vel scelerisque velit vehicula vitae. Vestibulum efficitur fringilla diam eget efficitur. Nunc suscipit est nec tortor porta tristique. Nam vestibulum sem cursus viverra blandit. Nunc quis pellentesque enim. Donec porttitor quam ac auctor auctor. In efficitur ultricies lorem eu pellentesque.',
      },
     {
        userId: 6,
        title: 'Fancy Pens!',
        category: 'art',
        subTitle: 'From different colors to different shapes, help us create any and all pens!',
        image: 'https://picsum.photos/400/250',
        targetLaunchDate: '04-2029',
        fundingCurrent: 4127,
        fundingGoal: 560000,
        story: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eleifend finibus ultrices. Donec volutpat venenatis auctor. Nam vehicula massa nulla, vel scelerisque velit vehicula vitae. Vestibulum efficitur fringilla diam eget efficitur. Nunc suscipit est nec tortor porta tristique. Nam vestibulum sem cursus viverra blandit. Nunc quis pellentesque enim. Donec porttitor quam ac auctor auctor. In efficitur ultricies lorem eu pellentesque.',
      },
     {
        userId: 2,
        title: 'Diet water. Experience true weight loss.',
        category: 'consumables',
        subTitle: 'Let make this a reality and collect!',
        image: 'https://picsum.photos/400/250',
        targetLaunchDate: '07-2025',
        fundingCurrent: 1400,
        fundingGoal: 1980000,
        story: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eleifend finibus ultrices. Donec volutpat venenatis auctor. Nam vehicula massa nulla, vel scelerisque velit vehicula vitae. Vestibulum efficitur fringilla diam eget efficitur. Nunc suscipit est nec tortor porta tristique. Nam vestibulum sem cursus viverra blandit. Nunc quis pellentesque enim. Donec porttitor quam ac auctor auctor. In efficitur ultricies lorem eu pellentesque.',
      },
     {
        userId: 2,
        title: 'H2Gl0w - Glow in the dark water!',
        category: 'consumables',
        subTitle: 'Don\'t be the one to lose your cup of water during those cozy late nights.',
        image: 'https://picsum.photos/400/250',
        targetLaunchDate: '12-2024',
        fundingCurrent: 1400,
        fundingGoal: 10000,
        story: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin eleifend finibus ultrices. Donec volutpat venenatis auctor. Nam vehicula massa nulla, vel scelerisque velit vehicula vitae. Vestibulum efficitur fringilla diam eget efficitur. Nunc suscipit est nec tortor porta tristique. Nam vestibulum sem cursus viverra blandit. Nunc quis pellentesque enim. Donec porttitor quam ac auctor auctor. In efficitur ultricies lorem eu pellentesque.',
      }
]
